title: Sasha's Portfolio
description: Projects for class
url: "https://sashaelle.github.io"
baseurl: "/portfolio"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

minimal_mistakes_skin: contrast

# This enables the top navigation
defaults:
  - scope:
      path: ""
    values:
      layout: single

sticky_nav: true

author:
  name: "Sasha Crawford"
  bio: "Student in [Major]. Interested in [topics]."
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/sashaelle"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:you@example.com"
