title: Sasha Crawford
description: Portfolio
url: "https://sashaelle.github.io"
baseurl: "/portfolio"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

minimal_mistakes_skin: contrast

# This enables the top navigation
defaults:
  - scope:
      path: ""
    values:
      author_profile: true
      layout: single

sticky_nav: true

author:
  name: "Sasha Crawford"
  bio: "Student in [Major]. Interested in [topics]."
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/sasha-crawford/"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:scrawfordcareer@gmail.com"
