title: SC
description: Portfolio
url: "https://sashaelle.github.io"
baseurl: "/portfolio"

favicon: "/portfolio/assets/images/icon.png"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

minimal_mistakes_skin: contrast

defaults:
  - scope:
      path: ""
    values:
      author_profile: true
      layout: single

author:
  name: "Sasha Crawford"
  bio: "Computer Science Major at DeSales University, graduating May 2026, with a passion for cyber security."
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/sasha-crawford/"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:scrawfordcareer@gmail.com"
